services:
  postgres:
    image: postgres:15-bullseye
    environment:
      POSTGRES_USER: dealls
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres-data:/data/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dealls" ]
      interval: 5s
      timeout: 5s
      retries: 5
    network_mode: host

  redis:
    command: sh -c "redis-server --appendonly yes"
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    network_mode: host

volumes:
  postgres-data:
  redis-data:
